version: '3'
services:
  web:
    # build: web/
    image: helpbuttons/helpbuttons-web:main
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - external_network
      - internal_network

  api:
    # build: api/
    image: helpbuttons/helpbuttons-api:main
    volumes:
      - config:/app/config/:rw
      - uploads:/app/uploads
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
    networks:
      - internal_network
    # ports: 
    #  - 3001:3001

  db:
    # build: postgres/
    image: helpbuttons/helpbuttons-psql:main
    restart: always
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=doesntmatter
      - POSTGRES_DB=hb-db
    volumes:
      - db:/var/lib/postgresql/data:rw
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - internal_network
      # - external_network
    #uncomment if using docker-compose up db and yarn dev for backend and not docker-compose.dev
    # ports: 
    #  - 5432:5432

  redis:
    restart: always
    image: redis:7-alpine
    networks:
      - internal_network
    #  - external_network
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
    volumes:
      - redis:/data
    #ports: 
    # - 6379:6379

networks:
  external_network:
  internal_network:
    internal: true

volumes:
  db:
  uploads:
  config:
  redis:
